src/os/Os.h File Reference
Main header for OS module.
Functions
void OS_init (void)
Initialize the OS.
Detailed Description
Main header for OS module.
Version
$Id: Os.h 294 2024-01-30 10:28:46Z leglaz $
Function Documentation
void OS_init (void)
Initialize the OS.
References Scheduler_init(), SoftTimerHandler_init(), and SoftTimerHandler_update().