src/os/Os.c File Reference
OS main module.
#include `os/Os.h`
*
#include `os/Scheduler.h`
*
#include `os/SoftTimer.h`
*
#include `hal/TickTimer.h`
*
Functions
void OS_init (void)
Initialize the OS.
Detailed Description
OS main module.
Version
$Id: Os.c 281 2024-01-12 12:09:03Z leglaz $
Function Documentation
void OS_init (void)
Initialize the OS.
References Scheduler_init(), SoftTimerHandler_init(), and SoftTimerHandler_update().