src/os/SoftTimer.c File Reference
SoftTimer implementation.
#include `os/SoftTimer.h`
*
#include `hal/TickTimer.h`
*
#include <util/atomic.h>
*
Macros
#define SOFT_TIMER_MAX_TIMER (10u)
Maximum number of soft timers.
Functions
void SoftTimer_init (SoftTimer *pSoftTimer)
Initialize a soft timer structure.
SoftTimer_Ret SoftTimer_start (SoftTimer *pSoftTimer, UInt16 thresHold)
Start a soft timer with a countdown value.
SoftTimer_Ret SoftTimer_Stop (SoftTimer *pSoftTimer)
Update a soft timer (interrupt context!).
void SoftTimer_Update (SoftTimer *pSoftTimer)
Update a soft timer (interrupt context!).
SoftTimer_Ret SoftTimer_restart (SoftTimer *pSoftTimer)
Update a soft timer with threshHold from former start call.
UInt16 SoftTimer_get (SoftTimer *pSoftTimer)
Get current countdown value of a soft timer.
void SoftTimerHandler_init ()
Initialize the soft timer handler.
SoftTimer_Ret SoftTimerHandler_register (SoftTimer *pNewSoftTimer)
Register a soft timer with the handler.
SoftTimer_Ret SoftTimerHandler_unRegister (SoftTimer *pSoftTimerToRemove)
De-Register a soft timer from the handler.
void SoftTimerHandler_update ()
Update all registered soft timer (interrupt context!).
UInt64 SoftTimer_getTimestampMs ()
Get the current value of the tick Counter in micro seconds since startup.
Detailed Description
SoftTimer implementation.
For a detailed description see the detailed description in SoftTimer.h.
Version
$Id: SoftTimer.c 281 2024-01-12 12:09:03Z leglaz $
Function Documentation
UInt16 SoftTimer_get (SoftTimer * pSoftTimer)
Get current countdown value of a soft timer.
Parameters
in pSoftTimer A soft timer structure.
References tag_SoftTimer::counter.
UInt64 SoftTimer_getTimestampMs (void)
Get the current value of the tick Counter in micro seconds since startup.
Returns
tick counter value in microseconds.
void SoftTimer_init (SoftTimer * pSoftTimer)
Initialize a soft timer structure.
Parameters
in pSoftTimer A soft timer structure.
References tag_SoftTimer::counter, SOFT_TIMER_UNREGISTERED, tag_SoftTimer::state, and tag_SoftTimer::threshHold.
SoftTimer_Ret SoftTimer_restart (SoftTimer * pSoftTimer)
Update a soft timer with threshHold from former start call.
Parameters
in pSoftTimer A soft timer structure.
References SoftTimer_start(), and tag_SoftTimer::threshHold.
SoftTimer_Ret SoftTimer_start (SoftTimer * pSoftTimer, UInt16 thresHold)
Start a soft timer with a countdown value.
Parameters
in pSoftTimer A soft timer structure.
in thresHold The start value of the count down.
References tag_SoftTimer::counter, SOFT_TIMER_RUNNING, SOFT_TIMER_UNREGISTERED, SOFTTIMER_RET_NOTREGISTERED, SOFTTIMER_RET_SUCCESS, tag_SoftTimer::state, and tag_SoftTimer::threshHold.
Referenced by SoftTimer_restart().
SoftTimer_Ret SoftTimer_Stop (SoftTimer * pSoftTimer)
Update a soft timer (interrupt context!).
Parameters
in pSoftTimer A soft timer structure.
References SOFT_TIMER_STOPPED, SOFT_TIMER_UNREGISTERED, SOFTTIMER_RET_NOTREGISTERED, SOFTTIMER_RET_SUCCESS, and tag_SoftTimer::state.
void SoftTimer_Update (SoftTimer * pSoftTimer)
Update a soft timer (interrupt context!).
Parameters
in pSoftTimer A soft timer structure.
References tag_SoftTimer::counter, SOFT_TIMER_RUNNING, and tag_SoftTimer::state.
SoftTimer_Ret SoftTimerHandler_register (SoftTimer * pSoftTimer)
Register a soft timer with the handler.
Parameters
in pSoftTimer A soft timer structure.
References NULL, SOFT_TIMER_MAX_TIMER, SOFT_TIMER_STOPPED, SOFTTIMER_RET_ALREADYREGISTERED, SOFTTIMER_RET_NOMORETIMERS, SOFTTIMER_RET_SUCCESS, and tag_SoftTimer::state.
SoftTimer_Ret SoftTimerHandler_unRegister (SoftTimer * pSoftTimer)
De-Register a soft timer from the handler.
Parameters
in pSoftTimer A soft timer structure.
References NULL, SOFT_TIMER_MAX_TIMER, SOFTTIMER_RET_SUCCESS, and SOFTTIMER_RET_UNKNOWNTIMER.
void SoftTimerHandler_update (void)
Update all registered soft timer (interrupt context!).
References tag_SoftTimer::counter, NULL, SOFT_TIMER_MAX_TIMER, SOFT_TIMER_RUNNING, and tag_SoftTimer::state.
Referenced by OS_init().