@startuml
left to right direction
actor "user" as h
actor "track" as t

rectangle System-Robot {
  usecase "Run Race" as UC1
  usecase "Mode Switch" as UC2
  usecase "Calibration" as UC3
  usecase "output information" as UC4
  
h --> UC1 : starts
UC4 --> h
h --> UC2
UC1 --> t

t --> UC3
h --> UC3

}


@enduml 
